### ISSUE TITLE
ERROR: FILE NOT FOUND

### ISSUE THREAD

**Issue by nosnowowie93347** [Chik3r/tModPorter#1]
when using your tModPorter tool, I'm getting the following error:

https://paste.gg/p/anonymous/3bd674df6956490b80afa70a73e52d7a

Using .NET 5.0.

**Comment by nosnowowie93347** [comment]
Ha i just had to install a NuGet package. Never mind.

**Comment by nosnowowie93347** [comment]
Now i'm getting this error after installing the package:

https://paste.gg/p/anonymous/0ae81348587a4560ac6fd03fda4078bd

**Comment by Chik3r** [comment]
It seems I forgot to update some packages, should be fixed now

**Comment by nosnowowie93347** [comment]
alright
