### ISSUE TITLE
Console says that path doesn't exist when it exists

### ISSUE THREAD

**Issue by ghost** [Chik3r/tModPorter#11]

**Comment by Chik3r** [comment]
Hello, the version of tModPorter in this repository has not been updated in a while, and it is currently being developed in the main [tModLoader GitHub](https://github.com/tModLoader/tModLoader/tree/1.4/tModPorter/tModPorter). You should try using the version of tModPorter available there, as it may have already fixed your issue. If it still doesn't work, I recommend you create an issue on the tModLoader GitHub with more details, or you send a message to the tModPorter discord thread (under the collaborators channel) in the tModLoader discord.
